### ISSUE TITLE
Can't get the "Command-click on tokens to view in Code Story" to work

### ISSUE THREAD

**Issue by agrublev** [dperetti/atom-codestory#2]
Really wanted to use the Atom package to easily jump into Code Story with the tokens :( tried everything possible and no luck clicking with Cmd to open Code Story see attached
![triedeverything](https://user-images.githubusercontent.com/801433/53701763-0132eb80-3db5-11e9-8ae3-1ca80ee49b05.gif)

I am a premium user, order id LAC190303-3275-57119

**Comment by dperetti** [comment]
Fixed in v0.3.1.
